### ISSUE TITLE
node_modules conflict

### ISSUE THREAD

**Issue by mdelclaro** [Yamilquery/react-native-timekeeper#2]
When running npm start to run the metro bundler I get this:

```
Looking for JS files in
   C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin

Loading dependency graph...(node:3768) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\react-native-timekeeper\node_modules\react-native\package.json collides with C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\react-native\package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\jest-haste-map\build\index.js:569:17)
    at workerReply (C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\jest-haste-map\build\index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:3768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3768) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\react-native-timekeeper\node_modules\react-native\package.json collides with C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\react-native\package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\jest-haste-map\build\index.js:569:17)
    at workerReply (C:\Users\Developer 3\Desktop\dev\motoapp-mobile-windows\MotoAppWin\node_modules\jest-haste-map\build\index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:3768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by mdelclaro** [comment]
I just deleted the `/node_modules` from `/node_modules/react-native-timekeeper/` and it has worked.
